"""add hex to car_colors

Revision ID: 40085e873bc4
Revises: 7c6f7d24fd26
Create Date: 2025-11-07 14:09:07.554059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40085e873bc4'
down_revision: Union[str, Sequence[str], None] = '7c6f7d24fd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_colors', sa.Column('hex', sa.String(length=7), nullable=False))
    op.create_unique_constraint(None, 'car_colors', ['hex'])
    op.create_unique_constraint(None, 'car_colors', ['color'])
    op.create_unique_constraint(None, 'clients', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'car_colors', type_='unique')
    op.drop_constraint(None, 'car_colors', type_='unique')
    op.drop_column('car_colors', 'hex')
    # ### end Alembic commands ###
